name: MERN CI/CD Pipeline with Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for backend
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Set up Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Set up Docker Compose for MongoDB
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          echo 'version: "3"
          services:
            mongo:
              image: mongo:latest
              ports:
                - 27017:27017
              healthcheck:
                test: "exit 0"
                interval: 10s
                retries: 5' > docker-compose.yml
          docker-compose up -d

      - name: Wait for MongoDB to start
        run: sleep 20s

      - name: Check MongoDB logs if failure
        if: failure()
        run: docker logs $(docker-compose ps -q mongo)

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest

      - name: Build and push frontend Docker image
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down
